# Generated by Django 3.1 on 2020-12-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isInSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
