# Generated by Django 3.1 on 2021-01-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210104_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_total',
            field=models.FloatField(default=0),
        ),
    ]
