# Generated by Django 3.1.5 on 2021-01-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.CharField(default='images/watch.png', max_length=1000),
        ),
    ]
